### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by TonyWuu** [nornagon/electron-minidump#1]
Hey @nornagon! Any reason this is hardcoded for `win32` platform?
```
const electronMinidump = async (options) => {
  const {version, quiet, force, file} = options
  const platform = 'win32'
```
Just curious because I swapped it with `darwin` and it seems to work fine for MacOS minidumps.

Also, is this meant to serve as a replacement for [symbolicate-mac](https://github.com/electron/symbolicate-mac)?

**Comment by nornagon** [comment]
This is not a replacement for symbolicate-mac. That repo works on textual dumps, such as those provided in macOS system crash reports or samples from Activity Monitor. This repo works on minidumps.

This repo should be generalized to work for non-windows platforms. I have some of that change locally on a machine I don't currently have access to due to COVID-19 😭

**Comment by nornagon** [comment]
I'll reopen this as this tool still doesn't work on non-windows minidumps without modification.

**Comment by TonyWuu** [comment]
Thanks @nornagon. Off the top of your head, other than the changes I mentioned above, is there anything else that needs to be done to get this working for MacOS only? Seems to be working for me, unless I'm missing something.

**Comment by nornagon** [comment]
Well, it needs to be parameterized for platform, and should support all the platforms and architectures that Electron supports: darwin {x64}, mas {x64}, linux {arm64,armv7l,ia32,x64}, win32 {arm64,ia32,x64}. Besides the command-line argument parsing needed to expose those options, the rest of the code should work fine once the correct symbols are downloaded.
